name: Shopify AI Blog

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  generate_and_post_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python ortamını kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gereken paketleri yükle
        run: pip install -r requirements.txt

      - name: Blog yazısını oluştur ve Shopify’a gönder
        run: python shopify_blog.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
